### ISSUE TITLE
getZoneStatus(via Orb)

### ISSUE THREAD

**Issue by gary-albano** [haruny/adt-pulse-mqtt#40]
Been using this for a long time, and now getting this error, it just dies. not much else I can say, but love this, and like to get it working, I have triggers that use the ADT sensors.

Anything I can do to help, let me know. 

```
1/21/2021, 10:06:58 PM Pulse.Sync: Sync stuck?
1/21/2021, 10:06:59 PM Pulse: Authentication Success
1/21/2021, 10:06:59 PM Pulse: updateAll
1/21/2021, 10:06:59 PM Pulse.getAlarmStatus: Getting Alarm Statuses
1/21/2021, 10:06:59 PM Pulse.Sync: Syncing 2-0-0
1/21/2021, 10:06:59 PM Pulse: updateAll
1/21/2021, 10:06:59 PM Pulse.getAlarmStatus: Getting Alarm Statuses
1/21/2021, 10:06:59 PM: Pushing alarm state: disarmed to home/alarm/state
1/21/2021, 10:06:59 PM Pulse.getDeviceStatus: Getting Device Statuses
1/21/2021, 10:06:59 PM Pulse.getZoneStatus(via Orb): Getting Zone Statuses
1/21/2021, 10:06:59 PM Pulse.getDeviceStatus No other devices found
1/21/2021, 10:06:59 PM Pulse.getDeviceStatus: Getting Device Statuses
1/21/2021, 10:06:59 PM Pulse.getZoneStatus(via Orb): Getting Zone Statuses
/usr/src/app/node_modules/cheerio/lib/parse.js:38
      content.forEach(function (node) {
              ^

TypeError: content.forEach is not a function
    at parse (/usr/src/app/node_modules/cheerio/lib/parse.js:38:15)
    at Function.exports.load (/usr/src/app/node_modules/cheerio/lib/static.js:39:14)
```

**Comment by gary-albano** [comment]
I can log into the ADT site, and I can see it trying on the logs from ADT as well
```
Version
core-2021.1.4
```

**Comment by digitalcraig** [comment]
The error occurs in parsing https://portal.adtpulse.com/myhome/20.0.0-244/ajax/orb.jsp. Does that page show all of your sensors? Has anything changed in your environment? Did you upgrade versions of anything?

Are you running as an addon or standalone in docker? Can you post a redacted version of your addon configuration or options.json file?

**Comment by gary-albano** [comment]
Page renders. shows my sensors.
I generally upgrade the core often when ever new patches come out, I am at the current version now. `core-2021.1.4`
running the addon. `Current version: 2.3.0` 
I think that answers the questions, let me know if I'm missing something, 
And huge thanks for replying so quickly.

**Comment by gary-albano** [comment]
```
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
pulse_login:
  username: redacted 
  password: redacted 
mqtt_host: redacted 
mqtt_url: ''
mqtt_connect_options:
  username: redacted 
  password: redacted 
alarm_state_topic: home/alarm/state
alarm_command_topic: home/alarm/cmd
zone_state_topic: adt/zone
smartthings_topic: smartthings
smartthings: false
```
